<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$ciencia = [
"titulo" => "CIENTIFICOS DE LA NBA",
"autor" => "MICHAEL B JORDAN ",
"resumen" => "M.B.JORDAN ANOTA 3 GOLES DE 50 YARDAS",
];
?>
