<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$cultura = [
"titulo" => "MINISTRO DE CULTURA",
"autor" => "UN ANONIMO",
"resumen" => "MINISTRO DE CULTURA MUERE EN LETHAL COMPANY",
];
?>
