<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$gente = [
"titulo" => "PERSONAS ZOMBIES",
"autor" => "NSA",
"resumen" => "VIRUS ZOMBIE CONTAGIA A ALUMNO DE LA UNS(TEEMO)",
];
?>
