<?php
/*****
SUSTITUYE LAS XXX POR UN VALOR DE UNA NOTICIA DE INTERES EN ESTA CATEGORIA
*****/

$television = [
"titulo" => "VIDEO ESCANDALO",
"autor" => "BAJITO",
"resumen" => "SE VIRALIZA VIDEO DE BAJITO CON CASTILLOOOOOO!",
];
?>
